s = set()
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))
n =input("Enter number 1:")
s.add(int(n))

print(s)